-- ALIE metadata store. Plain SQL, no SQLite-isms (PRD §13.4) — no AUTOINCREMENT, no
-- WITHOUT ROWID, no INSERT OR REPLACE. Ids are generated by the application so the same
-- DDL runs on Postgres when the metadata seam moves.

CREATE TABLE IF NOT EXISTS cases (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    primary_pack  TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bundles (
    id            TEXT PRIMARY KEY,
    case_id       TEXT NOT NULL REFERENCES cases(id),
    filename      TEXT NOT NULL,
    -- The upload folder label (`Médical`, `CHUM`, `TAT`). Becomes the locator name in
    -- column 2; it is not cosmetic (§4.1).
    folder_label  TEXT NOT NULL,
    content_hash  TEXT NOT NULL,
    page_count    INTEGER NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS bundles_case ON bundles(case_id);

CREATE TABLE IF NOT EXISTS pages (
    bundle_id      TEXT NOT NULL REFERENCES bundles(id),
    pdf_index      INTEGER NOT NULL,
    printed_label  TEXT,
    width          REAL NOT NULL,
    height         REAL NOT NULL,
    char_count     INTEGER NOT NULL,
    parse_source   TEXT NOT NULL,
    producer       TEXT NOT NULL,
    PRIMARY KEY (bundle_id, pdf_index)
);

-- Blocks: parse output, immutable, page/bbox anchored. Reparse replaces wholesale.
CREATE TABLE IF NOT EXISTS blocks (
    id            TEXT PRIMARY KEY,
    bundle_id     TEXT NOT NULL REFERENCES bundles(id),
    pdf_index     INTEGER NOT NULL,
    type          TEXT NOT NULL,
    text          TEXT NOT NULL,
    x0            REAL NOT NULL,
    y0            REAL NOT NULL,
    x1            REAL NOT NULL,
    y1            REAL NOT NULL,
    source        TEXT NOT NULL,
    confidence    REAL NOT NULL,
    ord           INTEGER NOT NULL,
    attrs         TEXT NOT NULL,
    producer      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS blocks_page ON blocks(bundle_id, pdf_index, ord);

-- Manifest: report units, classes, dates, regime tags, and every human correction.
-- Survives re-runs. This is the product (§4.5).
CREATE TABLE IF NOT EXISTS units (
    id                TEXT PRIMARY KEY,
    case_id           TEXT NOT NULL REFERENCES cases(id),
    bundle_id         TEXT NOT NULL REFERENCES bundles(id),
    pages             TEXT NOT NULL,          -- JSON array; a set, not a range (§8.3)
    doc_class         TEXT NOT NULL,
    class_confidence  REAL NOT NULL,
    class_source      TEXT NOT NULL,
    regime            TEXT NOT NULL,          -- per unit, not per case (§6.1)
    legibility        TEXT NOT NULL,
    author            TEXT,
    form_serial       TEXT,
    form_revision     TEXT,
    kind              TEXT NOT NULL,
    cited_by_unit_id  TEXT,
    excluded_by       TEXT,
    attrs             TEXT NOT NULL,
    producer          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS units_case ON units(case_id);

-- Every date found, with its role. A page does not have "a date" (§8.4).
CREATE TABLE IF NOT EXISTS unit_dates (
    id                TEXT PRIMARY KEY,
    unit_id           TEXT NOT NULL REFERENCES units(id),
    role              TEXT NOT NULL,
    readings          TEXT NOT NULL,          -- JSON array of ISO dates; >1 = ambiguous
    raw               TEXT NOT NULL,
    block_id          TEXT NOT NULL,
    span_start        INTEGER NOT NULL,
    span_end          INTEGER NOT NULL,
    pdf_index         INTEGER NOT NULL,
    confidence        REAL NOT NULL,
    century_inferred  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS unit_dates_unit ON unit_dates(unit_id);

-- The engine's date decision. Overwrites anything the model said (§8.4).
CREATE TABLE IF NOT EXISTS unit_row_dates (
    unit_id       TEXT PRIMARY KEY REFERENCES units(id),
    value         TEXT,
    status        TEXT NOT NULL,
    role          TEXT,
    rule          TEXT NOT NULL,
    explanation   TEXT NOT NULL,
    alternatives  TEXT NOT NULL           -- JSON array of ISO dates
);

-- Extracted records, from 4a (structured) or 4b (model). Every record stores the prompt
-- version *and* model that produced it (§7).
CREATE TABLE IF NOT EXISTS records (
    id              TEXT PRIMARY KEY,
    unit_id         TEXT NOT NULL REFERENCES units(id),
    field           TEXT NOT NULL,
    value           TEXT,
    stage           TEXT NOT NULL,          -- "4a" | "4b"
    block_id        TEXT,
    span_start      INTEGER,
    span_end        INTEGER,
    confidence      REAL NOT NULL,
    -- A derived record asserts something no span can carry: a count, or the *absence* of
    -- a field. It has no citation because there is no text to cite, which is a different
    -- thing from an uncited transcription. Render refuses to turn one into a bullet
    -- unless the row also carries a cited source (§3.5, §11.3).
    derived         INTEGER NOT NULL,
    rule            TEXT,
    epistemic_tag   TEXT,
    prompt_version  TEXT,
    model           TEXT,
    producer        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS records_unit ON records(unit_id, field);

-- A run is immutable and records its resolved flag set. Changing a flag creates a new
-- run (§9 rule 3).
CREATE TABLE IF NOT EXISTS runs (
    id            TEXT PRIMARY KEY,
    case_id       TEXT NOT NULL REFERENCES cases(id),
    status        TEXT NOT NULL,
    flags         TEXT NOT NULL,          -- JSON, fully resolved
    pack_versions TEXT NOT NULL,          -- JSON {pack: version}
    plan          TEXT NOT NULL,          -- JSON, the approved plan (§4.1)
    created_at    TEXT NOT NULL,
    finished_at   TEXT
);
CREATE INDEX IF NOT EXISTS runs_case ON runs(case_id);

-- Jobs never run inside an HTTP request — they go through this table even locally (§13.4).
CREATE TABLE IF NOT EXISTS jobs (
    id            TEXT PRIMARY KEY,
    run_id        TEXT NOT NULL REFERENCES runs(id),
    stage         TEXT NOT NULL,
    payload       TEXT NOT NULL,
    status        TEXT NOT NULL,          -- queued | running | done | failed
    attempts      INTEGER NOT NULL,
    created_at    TEXT NOT NULL,
    started_at    TEXT,
    finished_at   TEXT,
    error         TEXT
);
CREATE INDEX IF NOT EXISTS jobs_run ON jobs(run_id, status);

-- Row identity is derived from content and is deliberately stable across runs: that is
-- what lets a delta run diff against the approved version instead of producing a fresh
-- chronology, and what keeps approved rows sticky (§10.3). So the same `id` legitimately
-- appears in several runs, and the key is the pair.
CREATE TABLE IF NOT EXISTS rows_out (
    id               TEXT NOT NULL,
    run_id           TEXT NOT NULL REFERENCES runs(id),
    case_id          TEXT NOT NULL REFERENCES cases(id),
    date_value       TEXT,
    date_status      TEXT NOT NULL,
    date_rule        TEXT NOT NULL,
    date_explanation TEXT NOT NULL,
    date_alternatives TEXT NOT NULL,
    title            TEXT NOT NULL,
    author           TEXT,
    doc_class        TEXT NOT NULL,
    regime           TEXT NOT NULL,
    unit_ids         TEXT NOT NULL,
    illegible_reason TEXT,
    second_hand      INTEGER NOT NULL,
    -- Which claim this row belongs to: 1990 / 2011 / 2022 coexist in one file (§8.6).
    -- NULL is a real answer — a report predating every claim event is left unattributed
    -- rather than assigned to the nearest one.
    claim_event      TEXT,
    claim_event_rule TEXT,
    -- Excluded by a filter rule. The row still exists; exclusion is a status, not a
    -- deletion, and a deduplicated or filtered export carries a manifest of what was held
    -- back and why (§3.4, §10.1).
    excluded_by      TEXT,
    ord              INTEGER NOT NULL,
    PRIMARY KEY (run_id, id)
);
CREATE INDEX IF NOT EXISTS rows_run ON rows_out(run_id, ord);

CREATE TABLE IF NOT EXISTS row_bullets (
    id             TEXT PRIMARY KEY,
    run_id         TEXT NOT NULL REFERENCES runs(id),
    row_id         TEXT NOT NULL,
    ord            INTEGER NOT NULL,
    text           TEXT NOT NULL,
    confidence     REAL NOT NULL,
    rule           TEXT,
    bundle_id      TEXT NOT NULL,
    pdf_index      INTEGER NOT NULL,
    printed_label  TEXT,
    unit_id        TEXT NOT NULL,
    block_id       TEXT,
    span_start     INTEGER,
    span_end       INTEGER
);
CREATE INDEX IF NOT EXISTS row_bullets_row ON row_bullets(run_id, row_id, ord);

CREATE TABLE IF NOT EXISTS row_locators (
    run_id         TEXT NOT NULL REFERENCES runs(id),
    row_id         TEXT NOT NULL,
    ord            INTEGER NOT NULL,
    bundle_id      TEXT NOT NULL,
    folder_label   TEXT NOT NULL,
    pdf_index      INTEGER NOT NULL,
    printed_label  TEXT,
    unit_id        TEXT NOT NULL,
    PRIMARY KEY (run_id, row_id, ord)
);

-- Corrections write to the manifest, not the output (§10.2). Each is a labelled example
-- with a source span attached — design for that from day one; as a UI event log the
-- value is unrecoverable.
CREATE TABLE IF NOT EXISTS corrections (
    id            TEXT PRIMARY KEY,
    case_id       TEXT NOT NULL REFERENCES cases(id),
    subject_type  TEXT NOT NULL,          -- "unit" | "row_date" | "record" | "dupe_pair"
    subject_id    TEXT NOT NULL,
    field         TEXT NOT NULL,
    old_value     TEXT,
    new_value     TEXT,
    actor         TEXT NOT NULL,
    rule          TEXT,
    block_id      TEXT,
    span_start    INTEGER,
    span_end      INTEGER,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS corrections_subject ON corrections(subject_type, subject_id);

-- Not a debugging convenience; it is what the firm needs when asked how the chronology
-- was produced (§4.5).
CREATE TABLE IF NOT EXISTS audit (
    id              TEXT PRIMARY KEY,
    ts              TEXT NOT NULL,
    actor           TEXT NOT NULL,
    run_id          TEXT,
    subject_type    TEXT NOT NULL,
    subject_id      TEXT NOT NULL,
    action          TEXT NOT NULL,
    rule            TEXT,
    epistemic_tag   TEXT,
    prompt_version  TEXT,
    model           TEXT,
    detail          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_subject ON audit(subject_type, subject_id);
CREATE INDEX IF NOT EXISTS audit_run ON audit(run_id, ts);
